apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinyllama-1.1b-pvc # Note to use a unique name here!
  namespace: demo-llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 45Gi