apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpt-oss-20b-model-pvc # Note to use a unique name here!
  namespace: nutrient-example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 45Gi