apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nutrient-model # Note to use a unique name here!
  namespace: nutrient-example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 45Gi